apiVersion: v1
kind: ConfigMap
metadata:
  name: db2-nginx-config
  namespace: project-plato
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 5432;
            location / {
                proxy_pass http://localhost:5432;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
